# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wJjEdcMNpfk0QXrScgMtDLAEfxwif2xP
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
import pickle

# ------------------ Page Config ------------------
st.set_page_config(
    page_title="Credit Card Default Prediction",
    page_icon="💳",
    layout="wide"
)

# ------------------ Load Model ------------------
model = pickle.load(open("model.pkl", "rb"))
scaler = pickle.load(open("scaler.pkl", "rb"))

# ------------------ Title ------------------
st.title("💳 Credit Card Default Prediction")
st.markdown(
    "This Streamlit app predicts whether a customer will **default on credit card payment** using a trained **Gradient Boosting model**."
)

# ------------------ Sidebar Inputs ------------------
st.sidebar.header("Customer Information")

LIMIT_BAL = st.sidebar.number_input("Credit Limit", 10000, 1000000, 200000)
SEX = st.sidebar.selectbox("Gender", ["Male", "Female"])
EDUCATION = st.sidebar.selectbox("Education", [1, 2, 3, 4])
MARRIAGE = st.sidebar.selectbox("Marital Status", [1, 2, 3])
AGE = st.sidebar.number_input("Age", 18, 100, 30)

PAY_0 = st.sidebar.slider("Repayment Status (Last Month)", -2, 8, 0)
BILL_AMT1 = st.sidebar.number_input("Last Bill Amount", 0, 1000000, 50000)
PAY_AMT1 = st.sidebar.number_input("Last Payment Amount", 0, 1000000, 20000)

# Encoding (same logic as dataset)
SEX = 1 if SEX == "Male" else 2

# ------------------ Prediction ------------------
if st.sidebar.button("Predict Default"):

    input_data = np.array([[
        LIMIT_BAL, SEX, EDUCATION, MARRIAGE, AGE,
        PAY_0, BILL_AMT1, PAY_AMT1
    ]])

    input_scaled = scaler.transform(input_data)
    prediction = model.predict(input_scaled)

    st.subheader("🔍 Prediction Result")

    if prediction[0] == 1:
        st.error("❌ Customer is likely to DEFAULT")
    else:
        st.success("✅ Customer is NOT likely to default")

# ------------------ Dataset Preview ------------------
st.subheader("📊 Dataset Preview")

df = pd.read_csv("default_of_credit_card_clients.csv")
st.dataframe(df.head())

# ------------------ Footer ------------------
st.markdown("---")
st.markdown("Developed using **Streamlit & Machine Learning** 🚀")